/* 删除用户 */
DROP USER PB_DB_USER CASCADE;

/* 删除表空间 */
DROP TABLESPACE PB_TS_TABLE INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE PB_TS_INDEX INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;